import type { User, Event, Participant } from './types';

export const TESTIMONIALS_DATA = [
    {
      id: 1,
      quote: "Ser anfitrión en FiestaTalk me ha permitido conectar con gente increíble compartiendo mis pasiones. La plataforma es súper intuitiva y el soporte es de primera.",
      author: "Catalina Rojas",
      role: "Anfitriona de 'Misterios de Medianoche'",
    },
    {
      id: 2,
      quote: "Nunca pensé que podría generar ingresos haciendo lo que amo. FiestaTalk me dio las herramientas y la confianza para lanzar mis propios eventos de debate.",
      author: "Javier Morales",
      role: "Anfitrión de 'Debates Filosóficos'",
    },
];

export const EVENT_CATEGORIES = [
    "Misterio",
    "Debate",
    "Juegos",
    "Cultura",
    "Tecnología",
    "Social",
    "Creatividad",
    "Viajes",
    "Gastronomía",
    "Música",
    "Bienestar"
];

const initialUsers: Omit<User, 'id'>[] = [
    { name: "Admin General", email: "admin@fiestatalk.com", passwordHash: "Adm!n2025*FiestaTalk", role: 'admin', bio: "Administrador de la plataforma FiestaTalk.", avatarUrl: "https://i.imgur.com/2yaf2wb.png", enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [] },
    { name: "Carlos Santana", email: "carlos@host.com", passwordHash: "host123", role: 'host', bio: "Apasionado por los misterios y las buenas historias. ¡Prepárate para una noche de intriga!", avatarUrl: "https://i.pravatar.cc/150?u=carlos@host.com", enrolledEventIds: [], friends: [2, 3], friendRequestsReceived: [4], friendRequestsSent: [], ratings: [{userId: 2, userName: 'Ana Torres', stars: 5, comment: "¡Increíble anfitrión, muy entretenido!"},{userId: 3, userName: 'Pedro Pascal', stars: 4, comment: "Me gustó mucho la trama."}] },
    { name: "Ana Torres", email: "ana@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [1], friends: [1], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=ana@user.com" },
    { name: "Pedro Pascal", email: "pedro@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [1], friends: [1], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=pedro@user.com" },
    { name: "Beatriz Luengo", email: "bea@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [1], avatarUrl: "https://i.pravatar.cc/150?u=bea@user.com" },
    { name: "Javier Morales", email: "javier@host.com", passwordHash: "host123", role: 'host', bio: "Amante del buen debate y las conversaciones que desafían el status quo. ¡Únete y comparte tu perspectiva!", avatarUrl: "https://i.pravatar.cc/150?u=javier@host.com", enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [] },
    { name: "Claudia Soto", email: "claudia@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=claudia@user.com" },
    { name: "Ricardo Vega", email: "ricardo@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=ricardo@user.com" },
    { name: "Sofia Reyes", email: "sofia@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=sofia@user.com" },
    { name: "Martin Romero", email: "martin@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=martin@user.com" },
    { name: "Valentina Gomez", email: "valentina@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=valentina@user.com" },
    { name: "Daniel Muñoz", email: "daniel@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=daniel@user.com" },
    { name: "Isabella Diaz", email: "isabella@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=isabella@user.com" },
    { name: "Matias Castro", email: "matias@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=matias@user.com" },
    { name: "Camila Flores", email: "camila@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=camila@user.com" },
    { name: "Benjamin Herrera", email: "benjamin@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=benjamin@user.com" },
    { name: "Antonia Castillo", email: "antonia@user.com", passwordHash: "user123", role: 'user', enrolledEventIds: [], friends: [], friendRequestsReceived: [], friendRequestsSent: [], avatarUrl: "https://i.pravatar.cc/150?u=antonia@user.com" },
];

export const USERS_DATA: User[] = initialUsers.map((user, index) => ({ ...user, id: index + 1 }));

const createEventDate = () => new Date(Date.now() + 60 * 1000).toISOString();

const initialEvents: Omit<Event, 'id' | 'moderator' | 'players' | 'participants' | 'date'>[] = [
    // --- Misterio ---
    { hostId: 2, title: "El Enigma del Faraón Dorado", description: "Viaja al antiguo Egipto y desvela los secretos de una tumba recién descubierta. Un asesinato, un tesoro y muchos sospechosos. ¿Podrás resolver el misterio?", category: "Misterio", imageUrl: "https://images.unsplash.com/photo-1563190823-37205435567a?w=600&q=80", duration: "2.5 Horas", price: "$5.000 CLP", maxPlayers: 8 },
    { hostId: 2, title: "Crimen en el Expreso de Medianoche", description: "Un lujoso viaje en tren se convierte en una pesadilla. Un pasajero es asesinado y todos son sospechosos. Interroga y descubre al culpable antes de llegar a la estación.", category: "Misterio", imageUrl: "https://images.unsplash.com/photo-1506677810466-2442354a3296?w=600&q=80", duration: "3 Horas", price: "$4.500 CLP", maxPlayers: 10 },
    { hostId: 2, title: "El Secreto de la Mansión Blackwood", description: "Una herencia millonaria está en juego y un testamento ha desaparecido. Explora la decrépita mansión, resuelve acertijos y encuentra el documento antes de que sea tarde.", category: "Misterio", imageUrl: "https://images.unsplash.com/photo-1599335602339-9944f65c6978?w=600&q=80", duration: "2 Horas", price: "$3.000 CLP", maxPlayers: 12 },
    { hostId: 2, title: "La Conspiración del Hacker", description: "Un ciberataque amenaza con desestabilizar la ciudad. Trabaja en equipo para descifrar códigos, seguir pistas digitales y detener al hacker antes de su ultimátum.", category: "Misterio", imageUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80", duration: "2.5 Horas", price: "$4.000 CLP", maxPlayers: 10 },
    { hostId: 2, title: "Misterio en el Museo", description: "Una valiosa pieza de arte ha sido robada en plena noche. Analiza la escena del crimen, interroga al personal y descubre al ladrón en esta aventura gratuita.", category: "Misterio", imageUrl: "https://images.unsplash.com/photo-1582573733987-5a68a1851b31?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 15 },
    { hostId: 2, title: "El Caso del Escritor Desaparecido", description: "Un famoso autor de novelas de misterio se ha esfumado. ¿Es un truco publicitario o algo más siniestro? Sigue las pistas que dejó en su último manuscrito.", category: "Misterio", imageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&q=80", duration: "2 Horas", price: "Gratis", maxPlayers: 20 },
    { hostId: 2, title: "El Fantasma de la Ópera Digital", description: "Un misterioso 'fantasma' está saboteando una producción teatral online. Descubre quién se esconde detrás del avatar y cuáles son sus motivos.", category: "Misterio", imageUrl: "https://images.unsplash.com/photo-1596956450137-f2752b47155d?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 18 },
    { hostId: 2, title: "Aventura de Acertijos Urbanos", description: "Resuelve una serie de acertijos que te guiarán por lugares emblemáticos (virtualmente). Una forma divertida y gratuita de poner a prueba tu ingenio.", category: "Misterio", imageUrl: "https://images.unsplash.com/photo-1541512416315-797d3f1143b8?w=600&q=80", duration: "2 Horas", price: "Gratis", maxPlayers: 25 },
    // --- Debate ---
    { hostId: 6, title: "Debate Pro: IA y el Futuro del Trabajo", description: "Análisis profundo sobre cómo la IA está remodelando el mercado laboral. ¿Qué profesiones desaparecerán y cuáles surgirán? Un debate para mentes preparadas.", category: "Debate", imageUrl: "https://images.unsplash.com/photo-1620712943543-aeb89bf6192e?w=600&q=80", duration: "2 Horas", price: "$3.500 CLP", maxPlayers: 12 },
    { hostId: 6, title: "Ética y Privacidad en la Era Digital", description: "¿Cuál es el límite entre seguridad y vigilancia? Un debate moderado sobre el uso de nuestros datos por parte de empresas y gobiernos.", category: "Debate", imageUrl: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600&q=80", duration: "1.5 Horas", price: "$2.500 CLP", maxPlayers: 15 },
    { hostId: 6, title: "Cambio Climático: ¿Soluciones Reales?", description: "Discutamos con datos y propuestas concretas las soluciones más viables para enfrentar la crisis climática. Con la participación de un experto.", category: "Debate", imageUrl: "https://images.unsplash.com/photo-1502908859936-34d0b138f615?w=600&q=80", duration: "2 Horas", price: "$4.000 CLP", maxPlayers: 10 },
    { hostId: 6, title: "Filosofía Pop: El Significado en el Cine", description: "Analicemos los mensajes filosóficos ocultos en grandes obras de la cultura pop como Matrix o Black Mirror. Un debate para cinéfilos y pensadores.", category: "Debate", imageUrl: "https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=600&q=80", duration: "2 Horas", price: "$3.000 CLP", maxPlayers: 14 },
    { hostId: 6, title: "Debate Filosófico: ¿Somos Libres?", description: "Explora las profundidades del libre albedrío en un debate moderado. Analizaremos argumentos de filósofos clásicos y contemporáneos. No se requiere experiencia.", category: "Debate", imageUrl: "https://images.unsplash.com/photo-1494587422312-7a54a7a85583?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 12 },
    { hostId: 6, title: "Club de Debate Semanal: Actualidad", description: "Cada semana un tema nuevo. Únete a nuestra comunidad para debatir sobre las noticias más importantes de forma respetuosa y constructiva.", category: "Debate", imageUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 20 },
    { hostId: 6, title: "El Dilema de las Redes Sociales", description: "¿Nos unen o nos aíslan? Discutamos el impacto de las redes sociales en nuestra salud mental, relaciones y la sociedad. Abierto a todas las opiniones.", category: "Debate", imageUrl: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 18 },
    { hostId: 6, title: "Introducción al Pensamiento Crítico", description: "Aprende las bases para argumentar mejor, detectar falacias y formar opiniones más sólidas. Un taller práctico y gratuito para afilar tu mente.", category: "Debate", imageUrl: "https://images.unsplash.com/photo-1533750349088-247571368461?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 25 },
    // --- Juegos ---
    { hostId: 2, title: "Noche de Juegos de Improvisación", description: "¡Risas garantizadas! Únete a una sesión de juegos de improvisación teatral para todos los niveles. Perfecto para soltar el estrés y potenciar la creatividad.", category: "Juegos", imageUrl: "https://images.unsplash.com/photo-1579362456673-9e455c18d844?w=600&q=80", duration: "2 Horas", price: "$3.000 CLP", maxPlayers: 10 },
    { hostId: 2, title: "Torneo de Ajedrez Rápido Online", description: "Pon a prueba tu estrategia en nuestro torneo de ajedrez relámpago. Rondas rápidas de 10 minutos. ¡Que gane el mejor estratega!", category: "Juegos", imageUrl: "https://images.unsplash.com/photo-1580541832626-2a7131ee809f?w=600&q=80", duration: "3 Horas", price: "$1.500 CLP", maxPlayers: 16 },
    { hostId: 2, title: "Campeonato de Trivia General", description: "Cine, música, historia, ciencia... Demuestra tus conocimientos en este rápido y divertido campeonato de trivia por equipos. ¡Premios para los ganadores!", category: "Juegos", imageUrl: "https://images.unsplash.com/photo-1593344484962-796b55d73c52?w=600&q=80", duration: "1.5 Horas", price: "$2.000 CLP", maxPlayers: 20 },
    { hostId: 2, title: "Escape Room Virtual: El Laboratorio", description: "Estás atrapado en un laboratorio secreto y tienes 60 minutos para escapar. Resuelve puzzles y trabaja en equipo para encontrar la salida. ¿Lo lograrás?", category: "Juegos", imageUrl: "https://images.unsplash.com/photo-1576153729978-83b4f3b01b22?w=600&q=80", duration: "1 Hora", price: "$4.800 CLP", maxPlayers: 6 },
    { hostId: 2, title: "Tarde de Among Us con Amigos", description: "Tripulante o impostor, ¡la diversión está asegurada! Únete a nuestras partidas públicas y gratuitas de Among Us. No se requiere experiencia, solo ganas de reír.", category: "Juegos", imageUrl: "https://images.unsplash.com/photo-1613376285451-9360bd527393?w=600&q=80", duration: "2 Horas", price: "Gratis", maxPlayers: 10 },
    { hostId: 2, title: "Juegos de Mesa Clásicos Online", description: "Disfruta de una sesión relajada de juegos de mesa como Pictionary, Charadas o Scrabble en su versión online. Una forma perfecta de conocer gente nueva.", category: "Juegos", imageUrl: "https://images.unsplash.com/photo-1608111293233-4f0523a41d63?w=600&q=80", duration: "2.5 Horas", price: "Gratis", maxPlayers: 12 },
    { hostId: 2, title: "Introducción a los Juegos de Rol", description: "Si siempre quisiste probar Calabozos y Dragones pero no sabías por dónde empezar, esta es tu oportunidad. Una aventura para principiantes, guiada y gratuita.", category: "Juegos", imageUrl: "https://images.unsplash.com/photo-1579246198031-4a11f274a1ad?w=600&q=80", duration: "3 Horas", price: "Gratis", maxPlayers: 5 },
    { hostId: 2, title: "Competencia de Dibujo Rápido", description: "Una serie de rondas rápidas con temas divertidos. No importa si eres un artista o solo dibujas monigotes, ¡las risas están garantizadas!", category: "Juegos", imageUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 15 },
    // --- Cultura ---
    { hostId: 6, title: "Cine Foro: El Cine de Wes Anderson", description: "Analizaremos la estética, narrativa y personajes del aclamado director Wes Anderson. Una charla para cinéfilos y amantes del arte visual.", category: "Cultura", imageUrl: "https://images.unsplash.com/photo-1604177093836-3f1abbc08678?w=600&q=80", duration: "1.5 Horas", price: "$2.500 CLP", maxPlayers: 18 },
    { hostId: 6, title: "Historia del Arte: Del Renacimiento al Pop Art", description: "Un viaje visual a través de los movimientos artísticos más importantes de la historia. Descubre las obras y artistas que cambiaron el mundo.", category: "Cultura", imageUrl: "https://images.unsplash.com/photo-1547891654-e66ed711b934?w=600&q=80", duration: "2 Horas", price: "$3.800 CLP", maxPlayers: 20 },
    { hostId: 6, title: "Mitología Griega: Dioses, Héroes y Monstruos", description: "Sumérgete en las fascinantes historias de la mitología griega. Una charla interactiva sobre los mitos que han moldeado la cultura occidental.", category: "Cultura", imageUrl: "https://images.unsplash.com/photo-1633710892978-a53e46ab8254?w=600&q=80", duration: "1.5 Horas", price: "$3.000 CLP", maxPlayers: 15 },
    { hostId: 6, title: "Apreciación de Ópera para Principiantes", description: "Descubre la magia de la ópera. Escucharemos arias famosas, entenderemos las tramas y perderemos el miedo a este increíble género musical.", category: "Cultura", imageUrl: "https://images.unsplash.com/photo-1590700447545-381c84d3497d?w=600&q=80", duration: "1.5 Horas", price: "$2.800 CLP", maxPlayers: 20 },
    { hostId: 6, title: "Club de Lectura: Cien Años de Soledad", description: "Sumérgete en el realismo mágico de Gabriel García Márquez. Discutiremos los temas, personajes y el legado de esta obra maestra.", category: "Cultura", imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&q=80", duration: "2 Horas", price: "Gratis", maxPlayers: 15 },
    { hostId: 6, title: "Recorrido Virtual por el Museo del Louvre", description: "Acompáñanos en una visita guiada y gratuita por las salas más emblemáticas del Louvre. Descubre la historia detrás de la Mona Lisa, la Venus de Milo y más.", category: "Cultura", imageUrl: "https://images.unsplash.com/photo-1552560944-7389a1c1d88a?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 30 },
    { hostId: 6, title: "Poesía a Micrófono Abierto", description: "Un espacio seguro y acogedor para compartir tus poemas o simplemente escuchar a otros. Todos los estilos y niveles son bienvenidos.", category: "Cultura", imageUrl: "https://images.unsplash.com/photo-1470219556762-1771e7a929d2?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 20 },
    { hostId: 6, title: "Charla: La Historia del Rock and Roll", description: "Desde Elvis hasta Nirvana. Un repaso por las décadas, los artistas y las canciones que definieron la historia del rock. Prepara tus oídos.", category: "Cultura", imageUrl: "https://images.unsplash.com/photo-1524230659-c2162a143682?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 25 },
    // --- Tecnología ---
    { hostId: 2, title: "Introducción a Python: Tu Primer Programa", description: "Un taller práctico para no-programadores. Aprende los fundamentos de Python y escribe tus primeras líneas de código. No se necesita experiencia previa.", category: "Tecnología", imageUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80", duration: "2.5 Horas", price: "$4.500 CLP", maxPlayers: 10 },
    { hostId: 2, title: "Ciberseguridad para el Día a Día", description: "Aprende a proteger tus cuentas, evitar estafas y navegar de forma más segura. Una charla esencial con consejos prácticos que todos deberíamos conocer.", category: "Tecnología", imageUrl: "https://images.unsplash.com/photo-1544890225-2fde0e66ea0b?w=600&q=80", duration: "1.5 Horas", price: "$3.000 CLP", maxPlayers: 20 },
    { hostId: 2, title: "Diseño de Apps con Figma: Nivel Básico", description: "Descubre cómo diseñar el prototipo de una aplicación móvil sin escribir código. Aprenderemos las herramientas básicas de Figma en este taller interactivo.", category: "Tecnología", imageUrl: "https://images.unsplash.com/photo-1611262529941-471f652f2043?w=600&q=80", duration: "2 Horas", price: "$4.000 CLP", maxPlayers: 15 },
    { hostId: 2, title: "Blockchain más allá de las Criptomonedas", description: "Explora los usos revolucionarios de la tecnología blockchain en áreas como contratos inteligentes, logística y arte digital (NFTs).", category: "Tecnología", imageUrl: "https://images.unsplash.com/photo-1621402209314-b659d87cd078?w=600&q=80", duration: "1.5 Horas", price: "$3.500 CLP", maxPlayers: 25 },
    { hostId: 6, title: "Charla Tech: El Futuro de la IA", description: "Una discusión sobre las últimas tendencias en Inteligencia Artificial, su impacto en la sociedad y lo que nos depara el futuro. Apto para expertos y curiosos.", category: "Tecnología", imageUrl: "https://images.unsplash.com/photo-1531297484001-80022131c5a9?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 20 },
    { hostId: 6, title: "Tu Primera Página Web con HTML y CSS", description: "Descubre los fundamentos del desarrollo web en esta sesión introductoria. Crearemos una página web simple desde cero. ¡Totalmente gratis!", category: "Tecnología", imageUrl: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=600&q=80", duration: "2 Horas", price: "Gratis", maxPlayers: 18 },
    { hostId: 6, title: "Gadgets y Tendencias: Lo último en Tech", description: "Un repaso mensual y gratuito de los lanzamientos más interesantes, las últimas noticias del mundo tech y los gadgets que darán que hablar.", category: "Tecnología", imageUrl: "https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 30 },
    { hostId: 6, title: "Cómo funciona Internet: Una explicación simple", description: "Desde el clic hasta la pantalla: desmitificamos qué pasa cuando navegas por la web. Una charla para curiosos, sin necesidad de conocimientos técnicos.", category: "Tecnología", imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 25 },
    // --- Social ---
    { hostId: 2, title: "Speed Friending: Conexiones Rápidas", description: "Conoce gente nueva en una serie de conversaciones cortas y cronometradas. Una forma divertida y de baja presión para ampliar tu círculo social.", category: "Social", imageUrl: "https://images.unsplash.com/photo-1534308143481-c55f00be8bd7?w=600&q=80", duration: "1.5 Horas", price: "$2.000 CLP", maxPlayers: 16 },
    { hostId: 2, title: "Cata de Vinos Virtual (Kit Incluido)", description: "Una experiencia guiada por un sommelier. Recibe un kit con 3 vinos en casa y aprende a catar como un profesional. Cupos limitados.", category: "Social", imageUrl: "https://images.unsplash.com/photo-1554228402-21a41b8961a8?w=600&q=80", duration: "2 Horas", price: "$5.000 CLP", maxPlayers: 10 },
    { hostId: 2, title: "Noche de Citas Rápidas por Intereses", description: "Conoce a otros solteros que comparten tus gustos (cine, viajes, música...). Rondas temáticas para romper el hielo y encontrar esa conexión especial.", category: "Social", imageUrl: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=600&q=80", duration: "2 Horas", price: "$3.500 CLP", maxPlayers: 20 },
    { hostId: 2, title: "Club de la Comedia Online", description: "Una noche de monólogos con comediantes emergentes. Prepárate para reír a carcajadas desde tu sofá. ¡Apoya el talento local!", category: "Social", imageUrl: "https://images.unsplash.com/photo-1575509930310-9f12d1b7145b?w=600&q=80", duration: "1.5 Horas", price: "$2.800 CLP", maxPlayers: 30 },
    { hostId: 2, title: "Círculo de Conversación en Inglés", description: "Practica tu inglés en un ambiente amigable y sin presiones. Conversaremos sobre temas de actualidad para mejorar la fluidez. Nivel intermedio requerido.", category: "Social", imageUrl: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 10 },
    { hostId: 2, title: "Café Virtual y Charla Relajada", description: "Prepara tu bebida favorita y únete a una conversación tranquila para empezar el día. Sin temas fijos, solo buena compañía.", category: "Social", imageUrl: "https://images.unsplash.com/photo-1528699633785-50b6a50352e2?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 15 },
    { hostId: 2, title: "Amantes de las Mascotas: Comparte Historias", description: "Un espacio para que los dueños de mascotas (o simplemente amantes de los animales) compartan fotos, anécdotas y consejos. ¡Mascotas bienvenidas en cámara!", category: "Social", imageUrl: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 20 },
    { hostId: 2, title: "Grupo de Apoyo: Hablemos de Todo un Poco", description: "Un espacio seguro y confidencial para hablar de los altibajos de la vida. Escucha, comparte y siéntete acompañado. Moderado por un profesional.", category: "Social", imageUrl: "https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 12 },
    // --- Creatividad ---
    { hostId: 6, title: "Taller de Escritura Creativa", description: "Desbloquea a tu escritor interior. Exploraremos diferentes técnicas y ejercicios para que fluyan las ideas. Todos los niveles son bienvenidos.", category: "Creatividad", imageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&q=80", duration: "2 Horas", price: "$4.000 CLP", maxPlayers: 10 },
    { hostId: 6, title: "Aprende a Dibujar Caricaturas", description: "Un taller práctico para aprender los conceptos básicos del dibujo de caricaturas. ¡Saca el artista que llevas dentro y diviértete creando personajes!", category: "Creatividad", imageUrl: "https://images.unsplash.com/photo-1580130379624-3a069adbffc5?w=600&q=80", duration: "2 Horas", price: "$4.500 CLP", maxPlayers: 12 },
    { hostId: 6, title: "Introducción a la Acuarela desde Cero", description: "Descubre la belleza de la acuarela. Aprenderemos técnicas básicas de mezcla de colores y pinceladas para crear tu primera obra de arte.", category: "Creatividad", imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80", duration: "2.5 Horas", price: "$5.000 CLP", maxPlayers: 8 },
    { hostId: 6, title: "Fotografía con Celular: Captura como un Pro", description: "Sácale el máximo partido a la cámara de tu teléfono. Aprenderemos sobre composición, luz y edición para mejorar tus fotos al instante.", category: "Creatividad", imageUrl: "https://images.unsplash.com/photo-1554224154-260325c059a4?w=600&q=80", duration: "2 Horas", price: "$3.500 CLP", maxPlayers: 15 },
    { hostId: 6, title: "Club de Dibujo Semanal", description: "Un espacio relajado para dibujar juntos. Cada semana un tema diferente para inspirarnos. Comparte tu arte y conoce a otros creativos.", category: "Creatividad", imageUrl: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 20 },
    { hostId: 6, title: "Sesión de Brainstorming Grupal", description: "Atrapado en un proyecto? Trae tus ideas o problemas y recibe feedback constructivo de un grupo de mentes creativas. La inspiración está garantizada.", category: "Creatividad", imageUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 12 },
    { hostId: 6, title: "Origami para Relajarse", description: "Aprende el arte japonés del plegado de papel. Una actividad meditativa y gratuita para calmar la mente y crear algo hermoso con tus manos.", category: "Creatividad", imageUrl: "https://images.unsplash.com/photo-1515462277126-2ddde2624b12?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 25 },
    { hostId: 6, title: "Introducción al Storytelling", description: "Todos tenemos una historia que contar. Aprende las claves para estructurar una narrativa que atrape a tu audiencia. Charla introductoria gratuita.", category: "Creatividad", imageUrl: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 20 },
    // --- Viajes ---
    { hostId: 2, title: "Planifica tu Eurotrip Soñado", description: "Taller práctico para organizar tu primer viaje a Europa. Rutas, presupuestos, alojamiento y los mejores consejos de un viajero experto.", category: "Viajes", imageUrl: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=600&q=80", duration: "2 Horas", price: "$4.000 CLP", maxPlayers: 15 },
    { hostId: 2, title: "Japón para Principiantes: Cultura y Etiqueta", description: "Prepara tu viaje a Japón con esta guía cultural. Aprende frases básicas, costumbres y todo lo que necesitas saber para una experiencia inolvidable.", category: "Viajes", imageUrl: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=600&q=80", duration: "1.5 Horas", price: "$3.500 CLP", maxPlayers: 20 },
    { hostId: 2, title: "Fotografía de Viajes: Captura la Aventura", description: "Aprende a contar historias con tus fotos de viaje. Composición, equipo básico y consejos para capturar paisajes y retratos impresionantes.", category: "Viajes", imageUrl: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=600&q=80", duration: "2 Horas", price: "$4.200 CLP", maxPlayers: 12 },
    { hostId: 2, title: "Nómada Digital: Cómo Trabajar Viajando", description: "Descubre cómo financiar tus viajes trabajando de forma remota. Herramientas, consejos de productividad y testimonios de nómadas digitales.", category: "Viajes", imageUrl: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=600&q=80", duration: "1.5 Horas", price: "$3.800 CLP", maxPlayers: 18 },
    { hostId: 2, title: "Club de Viajeros: Historias de Asia", description: "Comparte tus historias y consejos de viaje, o escucha las aventuras de otros. Esta sesión se centra en viajes por el sudeste asiático. ¡Trae tus anécdotas!", category: "Viajes", imageUrl: "https://images.unsplash.com/photo-1508135810437-34ab3c7a3152?w=600&q=80", duration: "2 Horas", price: "Gratis", maxPlayers: 25 },
    { hostId: 2, title: "Charla: Recorriendo la Patagonia Chilena", description: "Descubre las maravillas de la Carretera Austral, Torres del Paine y más. Un viajero experimentado comparte su ruta, fotos y consejos.", category: "Viajes", imageUrl: "https://images.unsplash.com/photo-1529592429422-73b3a2157a4a?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 30 },
    { hostId: 2, title: "Intercambio de Idiomas para Viajeros", description: "Practica inglés, portugués, francés o el idioma que necesites para tu próximo viaje. Salas divididas por idioma para una práctica más efectiva.", category: "Viajes", imageUrl: "https://images.unsplash.com/photo-1463171379579-3f36b624f153?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 20 },
    { hostId: 2, title: "Mochileros 101: Viajar con Poco Presupuesto", description: "Compartimos los mejores trucos para ahorrar en vuelos, alojamiento y comida sin sacrificar la experiencia. ¡Viajar barato es posible!", category: "Viajes", imageUrl: "https://images.unsplash.com/photo-1527632911563-ee5b6d5344b6?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 25 },
    // --- Gastronomía ---
    { hostId: 2, title: "Taller de Cocina Virtual: Sabores de Tailandia", description: "Aprende a preparar un auténtico Pad Thai desde cero. Una clase interactiva donde cocinaremos juntos paso a paso. ¡Prepara tus ingredientes y a cocinar!", category: "Gastronomía", imageUrl: "https://images.unsplash.com/photo-1569058242253-92a8c3b177a2?w=600&q=80", duration: "2 Horas", price: "$5.000 CLP", maxPlayers: 8 },
    { hostId: 2, title: "Cata de Café de Especialidad", description: "Un barista profesional te guiará por los sabores y aromas de tres cafés de origen único. Aprende sobre métodos de preparación y perfiles de sabor.", category: "Gastronomía", imageUrl: "https://images.unsplash.com/photo-1511920183276-5942b03923b3?w=600&q=80", duration: "1.5 Horas", price: "$4.500 CLP", maxPlayers: 10 },
    { hostId: 2, title: "El Arte de la Pizza Casera", description: "Desde la masa perfecta hasta la combinación de ingredientes. Aprende los secretos para hacer pizzas deliciosas y crujientes en tu propio horno.", category: "Gastronomía", imageUrl: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=600&q=80", duration: "2 Horas", price: "$4.000 CLP", maxPlayers: 12 },
    { hostId: 2, title: "Coctelería Básica: Prepara Tragos Clásicos", description: "Sorprende a tus amigos en la próxima reunión. Aprende a preparar Mojitos, Daiquiris y otros cócteles clásicos con un bartender profesional.", category: "Gastronomía", imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80", duration: "1.5 Horas", price: "$3.800 CLP", maxPlayers: 15 },
    { hostId: 2, title: "Club de Recetas: Compartiendo Sabores", description: "Cada semana una temática (ej: pastas, postres). Trae tu receta estrella, comparte tus secretos culinarios y descubre nuevos platos.", category: "Gastronomía", imageUrl: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 20 },
    { hostId: 2, title: "Charla: Alimentación Consciente (Mindful Eating)", description: "Descubre cómo disfrutar más de la comida, reconocer las señales de tu cuerpo y mejorar tu relación con la alimentación. Charla introductoria gratuita.", category: "Gastronomía", imageUrl: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 25 },
    { hostId: 2, title: "Secretos de la Cocina de la Abuela", description: "Un espacio para compartir esas recetas tradicionales y trucos de cocina que pasan de generación en generación. ¡Pura nostalgia y sabor!", category: "Gastronomía", imageUrl: "https://images.unsplash.com/photo-1598103442387-035767425169?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 18 },
    { hostId: 2, title: "Cocina para Sobrevivir: Platos Fáciles y Baratos", description: "Ideal para estudiantes o independizados. Compartimos recetas rápidas, económicas y deliciosas para el día a día. ¡Comer bien no tiene por qué ser caro!", category: "Gastronomía", imageUrl: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 22 },
    // --- Música ---
    { hostId: 6, title: "Introducción a la Producción Musical con Ableton", description: "Da tus primeros pasos en el mundo de la producción musical. Aprenderemos la interfaz de Ableton Live y crearemos nuestro primer beat.", category: "Música", imageUrl: "https://images.unsplash.com/photo-1593697821252-1c92b7337982?w=600&q=80", duration: "2 Horas", price: "$5.000 CLP", maxPlayers: 10 },
    { hostId: 6, title: "Taller de Canto: Encuentra tu Voz", description: "Ejercicios de respiración, vocalización y técnica para mejorar tu canto. Un taller práctico para todos los niveles, ideal para perder el miedo a cantar.", category: "Música", imageUrl: "https://images.unsplash.com/photo-1589803478332-9a01683d4b6a?w=600&q=80", duration: "1.5 Horas", price: "$4.000 CLP", maxPlayers: 12 },
    { hostId: 6, title: "Apreciación de Jazz: Guía de Escucha", description: "Sumérgete en el mundo del jazz. Aprenderemos a reconocer estilos, instrumentos y a apreciar la improvisación. Con ejemplos de Miles Davis, Coltrane y más.", category: "Música", imageUrl: "https://images.unsplash.com/photo-1511192336575-5a79af67d629?w=600&q=80", duration: "1.5 Horas", price: "$3.000 CLP", maxPlayers: 20 },
    { hostId: 6, title: "Guitarra para Principiantes: Tus Primeros Acordes", description: "Aprende los acordes básicos y el ritmo para tocar tus primeras canciones. Un taller intensivo para empezar tu camino con la guitarra.", category: "Música", imageUrl: "https://images.unsplash.com/photo-1510915361894-db8b60106945?w=600&q=80", duration: "2 Horas", price: "$4.500 CLP", maxPlayers: 8 },
    { hostId: 6, title: "Noche de Jam Session Acústico", description: "Trae tu instrumento (¡o solo tu voz!) y únete a una sesión musical relajada. Tocaremos clásicos y crearemos música juntos. Para todos los amantes de la música.", category: "Música", imageUrl: "https://images.unsplash.com/photo-1520442352133-c2a4729c1626?w=600&q=80", duration: "2.5 Horas", price: "Gratis", maxPlayers: 20 },
    { hostId: 6, title: "Club de Escucha de Álbumes Clásicos", description: "Cada semana escuchamos y comentamos un álbum icónico de la historia de la música. Esta semana: 'The Dark Side of the Moon' de Pink Floyd.", category: "Música", imageUrl: "https://images.unsplash.com/photo-1549490349-8645c9a296ef?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 25 },
    { hostId: 6, title: "Descubre Nueva Música: Sesión Colaborativa", description: "Comparte esa canción que no puedes dejar de escuchar y descubre las joyas musicales de otros participantes. Todos los géneros son bienvenidos.", category: "Música", imageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80", duration: "1.5 Horas", price: "Gratis", maxPlayers: 20 },
    { hostId: 6, title: "Karaoke desde Casa", description: "¡Prepara el micrófono (o el cepillo de pelo) y canta tus canciones favoritas! Un espacio divertido y sin juicios para liberar a la estrella que llevas dentro.", category: "Música", imageUrl: "https://images.unsplash.com/photo-1567004233267-96a2b95c328b?w=600&q=80", duration: "2 Horas", price: "Gratis", maxPlayers: 15 },
    // --- Bienestar ---
    { hostId: 6, title: "Taller de Gestión del Estrés y Ansiedad", description: "Aprende técnicas prácticas de respiración, mindfulness y organización para manejar el estrés del día a día. Impartido por un coach de bienestar.", category: "Bienestar", imageUrl: "https://images.unsplash.com/photo-1598495494482-16b751419d20?w=600&q=80", duration: "1.5 Horas", price: "$4.000 CLP", maxPlayers: 15 },
    { hostId: 6, title: "Yoga Suave para Aliviar la Tensión", description: "Una clase de yoga restaurativo enfocada en estiramientos suaves y posturas relajantes para liberar la tensión acumulada en cuello, hombros y espalda.", category: "Bienestar", imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80", duration: "1 Hora", price: "$3.000 CLP", maxPlayers: 20 },
    { hostId: 6, title: "Introducción a la Nutrición Holística", description: "Descubre cómo la alimentación afecta no solo tu cuerpo, sino también tu mente y emociones. Consejos para una dieta más equilibrada y energética.", category: "Bienestar", imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17025?w=600&q=80", duration: "1.5 Horas", price: "$3.500 CLP", maxPlayers: 18 },
    { hostId: 6, title: "Journaling para la Claridad Mental", description: "Aprende diferentes técnicas de escritura terapéutica para organizar tus pensamientos, procesar emociones y establecer metas. No se requiere experiencia.", category: "Bienestar", imageUrl: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&q=80", duration: "1 Hora", price: "$2.500 CLP", maxPlayers: 20 },
    { hostId: 6, title: "Introducción a la Meditación Mindfulness", description: "Descubre técnicas de mindfulness para reducir el estrés y mejorar tu enfoque. Una sesión guiada y tranquila, perfecta para principiantes.", category: "Bienestar", imageUrl: "https://images.unsplash.com/photo-1506126613408-4e05860358de?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 30 },
    { hostId: 6, title: "Pausa Activa: Estiramientos en la Oficina", description: "Combate el sedentarismo con esta sesión gratuita de 30 minutos. Estiramientos simples que puedes hacer en tu silla para mejorar tu postura y energía.", category: "Bienestar", imageUrl: "https://images.unsplash.com/photo-1617462121634-d8a7281f6e25?w=600&q=80", duration: "30 Minutos", price: "Gratis", maxPlayers: 25 },
    { hostId: 6, title: "Círculo de Gratitud Semanal", description: "Un espacio para compartir y escuchar aquello por lo que estamos agradecidos. Una práctica simple pero poderosa para mejorar nuestro estado de ánimo.", category: "Bienestar", imageUrl: "https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 20 },
    { hostId: 6, title: "Charla: Higiene del Sueño para un Mejor Descanso", description: "Consejos y hábitos respaldados por la ciencia para combatir el insomnio y mejorar la calidad de tu sueño. Duerme mejor, vive mejor.", category: "Bienestar", imageUrl: "https://images.unsplash.com/photo-1530531238883-b71552a46433?w=600&q=80", duration: "1 Hora", price: "Gratis", maxPlayers: 30 },
];

export const EVENTS_DATA: Event[] = initialEvents.map((event, index) => {
    const host = USERS_DATA.find(u => u.id === event.hostId);
    if (!host) throw new Error("Host not found for event");

    // Create the participant object for the host
    const hostParticipant: Participant = {
        id: host.id,
        name: host.name,
        avatarUrl: host.avatarUrl || `https://i.pravatar.cc/150?u=${host.email}`
    };

    // Get all users who can be attendees (not the host)
    const potentialAttendees = USERS_DATA.filter(u => u.id !== event.hostId && u.role !== 'admin');

    // Determine a random number of attendees, ensuring it doesn't exceed maxPlayers
    const numberOfAttendees = Math.floor(Math.random() * (event.maxPlayers)); // From 0 to maxPlayers - 1

    // Shuffle and select the attendees
    const shuffledAttendees = potentialAttendees.sort(() => 0.5 - Math.random());
    const selectedAttendees = shuffledAttendees.slice(0, numberOfAttendees);

    // Create participant objects for the attendees
    const attendeeParticipants: Participant[] = selectedAttendees.map(user => ({
        id: user.id,
        name: user.name,
        avatarUrl: user.avatarUrl || `https://i.pravatar.cc/150?u=${user.email}`
    }));

    const eventWithId: Event = {
        ...(event as Omit<Event, 'id' | 'moderator' | 'players' | 'participants' | 'date' | 'date'>),
        id: index + 1,
        date: createEventDate(), // Use the new function to set a 1-minute countdown
        moderator: `Anfitrión: ${host.name}`,
        // The full list of participants for the call room includes the host and attendees
        participants: [hostParticipant, ...attendeeParticipants],
        // The "players" string should reflect the number of enrolled attendees
        players: `${attendeeParticipants.length}/${event.maxPlayers} Jugadores`,
    };
    return eventWithId;
});